### ISSUE TITLE
字段不能设置统一的驼峰转下划线规则

### ISSUE THREAD

**Issue by threefish** [mybatis-mapper/mapper#3]
```java
@Data
@Extend.Table("user")
public class User  {
    @Extend.Column(id = true)
    private Long id;
    @Extend.Column
    private String userName;
    @Extend.Column("sex")
    private String sex;
}
```

```yml
mybatis:
  configuration:
    map-underscore-to-camel-case: true
```
该参数 map-underscore-to-camel-case 不生效
